---
version: "2.0"

services:
  scheduler:
    image: skynetlabs/akash-mongo-scheduler:v1.0.1
    container_name: scheduler
    depends_on:
      - mongodb
    env:
      - MONGODB_DATABASE=akash_mongo
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=password
      - SKYNET_SEED=testingfordaniel11
      - SKYNET_DATAKEY=mongobackup

  mongodb:
    image: skynetlabs/akash-mongo-mongodb:v1.0.0
    restart: always
    container_name: mongodb
    expose:
      - port: 27017
        to:
          - global: true
          - service: scheduler

profiles:
  compute:
    scheduler:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    mongodb:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    dcloud:
      pricing:
        scheduler:
          denom: uakt
          amount: 10
        mongodb:
          denom: uakt
          amount: 10

deployment:
  scheduler:
    dcloud:
      profile: scheduler
      count: 1
  mongodb:
    dcloud:
      profile: mongodb
      count: 1
