version: "3.4"

services:
  scheduler:
    build:
      context: .
    container_name: scheduler
    volumes:
      - ./scripts:/scripts
      - ./crontab:/crontab
    depends_on:
      - mongodb
    env_file: .env

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: root-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
