version: "3.4"

services:
  scheduler:
    image: skynetlabs/akash-mongo-scheduler:v1.0.1
    container_name: scheduler
    depends_on:
      - mongodb
    environment:
      - MONGODB_DATABASE=akash_mongo
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=password
      - SKYNET_SEED=supersecret
      - SKYNET_DATAKEY=mongobackup

  mongodb:
    image: skynetlabs/akash-mongo-mongodb:v1.0.0
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
