version: "3.4"

services:
  scheduler:
    build:
      context: .
    volumes:
      - ./scripts:/scripts
      - ./crontab:/crontab
    depends_on:
      - mongodb
    env_file: .env

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    env_file: .env
